import Card from "./Card";
import shuffle from "../utilities/arrayMethods";

function Board({
  onClick,
  setBestScore,
  score,
  boolean,
  setScore,
  setBoolean,
  bestScore,
  win,
  setWin,
}) {
  const arrayOf = [
    <Card
      key={1}
      onClick={onClick}
      setBestScore={setBestScore}
      score={score}
      boolean={boolean}
      setBoolean={setBoolean}
      setScore={setScore}
      bestScore={bestScore}
      win={win}
      setWin={setWin}
      src={"https://www.memeatlas.com/images/pepes/pepe-hot-iron-phone.png"}
    />,
    <Card
      key={2}
      onClick={onClick}
      setBestScore={setBestScore}
      score={score}
      boolean={boolean}
      setBoolean={setBoolean}
      setScore={setScore}
      bestScore={bestScore}
      win={win}
      setWin={setWin}
      src={"https://www.memeatlas.com/images/pepes/pepe-constable-with-baton.png"}
    />,
    <Card
      key={3}
      onClick={onClick}
      setBestScore={setBestScore}
      score={score}
      boolean={boolean}
      setBoolean={setBoolean}
      setScore={setScore}
      bestScore={bestScore}
      win={win}
      setWin={setWin}
      src={"https://www.memeatlas.com/images/pepes/pepe-in-coffee-recursive-image.png"}
    />,
    <Card
      key={4}
      onClick={onClick}
      setBestScore={setBestScore}
      score={score}
      boolean={boolean}
      setBoolean={setBoolean}
      setScore={setScore}
      bestScore={bestScore}
      win={win}
      setWin={setWin}
      src={"https://www.memeatlas.com/images/pepes/pepe-toaster-head-closeup.png"}
    />,
    <Card
      key={5}
      onClick={onClick}
      setBestScore={setBestScore}
      score={score}
      boolean={boolean}
      setBoolean={setBoolean}
      setScore={setScore}
      bestScore={bestScore}
      win={win}
      setWin={setWin}
      src={"https://www.memeatlas.com/images/pepes/pepe-federal-pepe-investigator.jpg"}
    />,
    <Card
      key={6}
      onClick={onClick}
      setBestScore={setBestScore}
      score={score}
      boolean={boolean}
      setBoolean={setBoolean}
      setScore={setScore}
      bestScore={bestScore}
      win={win}
      setWin={setWin}
      src={"https://www.memeatlas.com/images/pepes/pepe-tv-station-interview-microphones.png"}
    />,
    <Card
      key={7}
      onClick={onClick}
      setBestScore={setBestScore}
      score={score}
      boolean={boolean}
      setBoolean={setBoolean}
      setScore={setScore}
      bestScore={bestScore}
      win={win}
      setWin={setWin}
      src={"https://www.memeatlas.com/images/pepes/pepe-french-bread.png"}
    />,
    <Card
      key={8}
      onClick={onClick}
      setBestScore={setBestScore}
      score={score}
      boolean={boolean}
      setBoolean={setBoolean}
      setScore={setScore}
      bestScore={bestScore}
      win={win}
      setWin={setWin}
      src={"https://www.memeatlas.com/images/pepes/pepe-ninja-turtle.jpg"}
    />,
    <Card
      key={9}
      onClick={onClick}
      setBestScore={setBestScore}
      score={score}
      boolean={boolean}
      setBoolean={setBoolean}
      setScore={setScore}
      bestScore={bestScore}
      win={win}
      setWin={setWin}
      src={"https://www.memeatlas.com/images/pepes/pepe-fren-zone.png"}
    />,
  ];

  return <>{shuffle(arrayOf)}</>;
}

export default Board;
